[package]
name = "circom-witnesscalc"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/iden3/circom-witnesscalc"

[features]
default = []
print_opcode = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"
ark-bn254 = { version = "0.5.0", features = ["std"] }
ark-ff = { version = "0.5.0", features = ["std", "asm"] }
ark-serialize = { version = "0.5.0", features = ["derive"] }
byteorder = "1.4.3"
rand = "0.8.5"
ruint = { version = "1.13.1", features = ["rand", "serde", "num-traits"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.64"
wtns-file = "0.1.5"
libc = "0.2.155"
# circom dependencies
#compiler = { path = "../circom/compiler" }
#code_producers = { path = "../circom/code_producers" }
#program_structure = { path = "../circom/program_structure" }
#parser = { path = "../circom/parser" }
#type_analysis = { path = "../circom/type_analysis" }
#constraint_generation = { path = "../circom/constraint_generation" }
compiler = { git = "https://github.com/olomix/circom.git", branch = "master" }
code_producers = { git = "https://github.com/olomix/circom.git", branch = "master" }
program_structure = { git = "https://github.com/olomix/circom.git", branch = "master" }
parser = { git = "https://github.com/olomix/circom.git", branch = "master" }
type_analysis = { git = "https://github.com/olomix/circom.git", branch = "master" }
constraint_generation = { git = "https://github.com/olomix/circom.git", branch = "master" }
prost = "0.13.1"
num-bigint = "0.4.6"
num-traits = "0.2.19"
anyhow = "1.0.97"
indicatif = "0.17.11"
memmap2 = "0.9.5"
tempfile = "3.19.1"
bincode = "2.0.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
# debug = true

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[build-dependencies]
bindgen = "0.70.1"
prost-build = "0.13.3"
